### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by fabianmoronzirfas** [fabianmoronzirfas/gestalten-in-code#34]
@piixelcat There is a broken link in your bart van der leck project. It refers to the code folder but there is no code. https://github.com/fabianmoronzirfas/gestalten-in-code/blame/master/projects/bart-van-der-leck/index.md#L143

You should commit the code as projects or remove the link.

**Comment by piixelcat** [comment]
@fabianmoronzirfas I created a pull request to commit the code as project. Should I create a new pull request for the updated index.md? I also added a nicer thumbnail image and found a small misspelling.

**Comment by fabianmoronzirfas** [comment]
Yes create a new PR please.

**Comment by fabianmoronzirfas** [comment]
@piixelcat can I close this issue?

**Comment by piixelcat** [comment]
@fabianmoronzirfas Yes! Fixed the link in my last PR some time ago.

**Comment by fabianmoronzirfas** [comment]
Top. 👍🏽
